project: patho_benchmark
experiment: Ablation_experiment_0
experiment_path: experiments
training_steps: 30000
log_interval: 1000
val_interval: 1000
multiprocessing: true
num_workers: 4
seed: 42
primary_metric: f1_score_macro
save_all_ckpts: false # watch out for memory

dataset:
  name: 'schuerch'
  path: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/schuerch_dataset_lmdb/lmdb
  split: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/schuerch_dataset_lmdb/splits/schuerch_dataset_split.csv
  label_dict: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/schuerch_dataset_lmdb/label_dict.json
  batch_size: 128
  uniform_class_sampling: False
  sample_excluded_classes: False

model:
  model_wrapper: SimpleSegmentationModel
  unfreeze_backbone: false

optimizer:
  name: AdamW
  params:
    lr: 3e-5
    weight_decay: 0.03
  warmup_steps: 1000

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 30000
    eta_min: 1e-6

loss_fn:
  name: CrossEntropyLoss
  params:
    label_smoothing: 0.05
    reduction: none
  class_weighting: true
  exclude_classes: [0]
