url: "MahmoodLab/UNI2-h"
patch_size: 14
pretrained: True
depth: 24
num_heads: 24
init_values: 1e-5
embed_dim: 1536
mlp_ratio: 5.33334
num_classes: 0
no_embed_class: True
reg_tokens: 8
dynamic_img_size: True
img_size: 224