project: patho_benchmark
experiment: uni_arctique_normalized_aug_1
wandb_mode: 'offline'
experiment_path: /home/fabian/projects/lab_hackathon_2024/experiments
training_steps: 300
log_interval: 10
val_interval: 10
multiprocessing: false
num_workers: 0
seed: 42
primary_metric: f1_score_macro

dataset:
  path: /raid55/data/arctique_dataset/arctique/arctique_lmdb
  split: /raid55/data/arctique_dataset/arctique/train_test_val_split.csv
  label_dict: /raid55/data/arctique_dataset/label_dict.json
  batch_size: 128

model:
  model_wrapper: SimpleSegmentationModel
  backbone: UNI
  unfreeze_backbone: false

optimizer:
  name: AdamW
  params:
    lr: 3e-5
    weight_decay: 0.03
  warmup_steps: 10

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 30000
    eta_min: 1e-6

loss_fn:
  name: CrossEntropyLoss
  params:
    label_smoothing: 0.05
    reduction: none
  class_weighting: true

  exclude_classes: [0]

augmentations:
  RandomHorizontalFlip:
    p: 0.5
  RandomVerticalFlip:
    p: 0.5
  RandomAffine:
    degrees: [0, 360]
    translate: 0.1
    scale: [0.8, 1.2]
    resample: BILINEAR
  RandomElasticTransform:
    kernel_size: [63, 63]
    sigma: [32.0, 32.0]
    alpha: [1.0, 1.0]
  HEDNormalize:
    sigma: 0.025
    bias: 0.05