project: patho_benchmark
experiment: unetr
experiment_path: experiments
training_steps: 3000
log_interval: 100
val_interval: 10
multiprocessing: false
num_workers: 0
seed: 42
primary_metric: f1_score_macro

dataset:
  name: 'lizard'
  path: tests/test_data/small_lizard_lmdb
  split: tests/test_data/small_lizard_train_test_val_split.csv
  label_dict: tests/test_data/label_dict.json
  batch_size: 8
  uniform_class_sampling: True
  sample_excluded_classes: False
  
model:
  model_wrapper: SimpleSegmentationModel
  backbone: virchow2
  unfreeze_backbone: false

optimizer:
  name: AdamW
  params:
    lr: 3e-5
    weight_decay: 0.03
  warmup_steps: 100

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 200000
    eta_min: 1e-6

loss_fn:
  name: CrossEntropyLoss
  params:
    label_smoothing: 0.05
    reduction: none
  class_weighting: false

  exclude_classes: [0]

  augmentations:
    RandomHorizontalFlip:
      p: 0.5
    RandomVerticalFlip:
      p: 0.5
    RandomRotation:
      - degrees: [0, 360]
        p: 0.5
        resample: NEAREST
    HEDNormalize:
      - sigma: 0.05
        bias: 0.1
