project: patho_benchmark
experiment: "DPT"
experiment_path: experiments
training_steps: 15000
log_interval: 10
val_interval: 150
multiprocessing: true
num_workers: 4
seed: 42
primary_metric: f1_score_macro
save_all_ckpts: false # watch out for storage
early_stopping: 1200
less_metrics: true
do_confmat: true

dataset:
  name: "pannuke"
  path: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/pannuke/pannuke_lmdb_no_pad
  split: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/pannuke/splits/train_test_val_split.csv
  label_dict: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/pannuke/label_dict.json
  batch_size: 16
  uniform_class_sampling: True
  sample_excluded_classes: False
  
model:
  model_wrapper: DPT
  backbone: uni #provgigapath, uni, uni2, musk, titan, virchow2, phikonv2
  unfreeze_backbone: false
  do_ms_aug: false

optimizer:
  name: AdamW
  params:
    lr: 3e-5
    weight_decay: 0.03
  warmup_steps: 1000

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10000
    eta_min: 1e-6

loss_fn:
  name: CrossEntropyLoss
  params:
    label_smoothing: 0.05
    reduction: none
  class_weighting: true

  exclude_classes: [0]

augmentations:
  RandomHorizontalFlip:
    p: 0.5
  RandomVerticalFlip:
    p: 0.5
  RandomAffine:
    degrees: [0, 360]
    translate: 0.1
    scale: [0.8, 1.2]  # Changed 0.2 to [min_scale, max_scale]
    resample: BILINEAR
  RandomElasticTransform:
    kernel_size: [63, 63]
    sigma: [32.0, 32.0]
    alpha: [1.0, 1.0]  # Changed from alpha_affine to alpha
  HEDNormalize:
    sigma: 0.025 # halved color aug
    bias: 0.05 # halved color aug
