project: patho_benchmark
experiment: uni_linear_1
experiment_path: experiments
training_steps: 20
log_interval: 10
val_interval: 1
multiprocessing: false
num_workers: 0
seed: 42
primary_metric: f1_score_macro

dataset:
  path: tests/test_data/small_lizard_lmdb
  split: tests/test_data/small_lizard_train_test_val_split.csv
  label_dict: tests/test_data/label_dict.json
  batch_size: 2
  num_workers: 0

model:
  model_wrapper: SimpleSegmentationModel
  backbone: UNI

optimizer:
  name: AdamW
  params:
    lr: 3e-5
    weight_decay: 0.03
  warmup_steps: 100

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 200000
    eta_min: 1e-6

loss_fn:
  name: CrossEntropyLoss
  params:
    label_smoothing: 0.05
