project: patho_benchmark
experiment: uni_frozen_lizard_linear_class_weighting_2_fabi
experiment_path: /fast/AG_Kainmueller/fabian/projects/hackathon_2024/experiments
training_steps: 30000
log_interval: 1000
val_interval: 1000
multiprocessing: true
num_workers: 4
seed: 42
primary_metric: f1_score_macro

dataset:
  path: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/lizard_dataset/lizard_tiled_lmdb/
  split: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/lizard_dataset/splits/lizard_default_train_test_val_split.csv
  label_dict: /fast/AG_Kainmueller/data/patho_foundation_model_bench_data/lizard_dataset/label_dict.json
  batch_size: 128

model:
  model_wrapper: SimpleSegmentationModel
  backbone: UNI
  unfreeze_backbone: false

optimizer:
  name: AdamW
  params:
    lr: 3e-5
    weight_decay: 0.03
  warmup_steps: 1000

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 30000
    eta_min: 1e-6

loss_fn:
  name: CrossEntropyLoss
  params:
    label_smoothing: 0.05
    reduction: none
  class_weighting: true

  exclude_classes: [0]