name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    name: Test
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/build.yaml
